url: https://imandicdev.github.io/imandic.github.io/
baseurl: /

# Site settings
title: Ilija Mandic - Software Engineering Professional
email: imandic@devtonomy.net
description: "Personal portfolio"


# Team names, titles and social links
peopple:
- name: Ilija Mandic
  pic: 2
  position: Lead Developer
  social:
    - title: github
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Kedrova 4
  - line: Belgrade, Serbia, 11000

# Build settings
markdown: kramdown
permalink: pretty
