url: https://github.io/imandicdev.github.io
baseurl: 

# Site settings
title: Ilija Mandic - Software Engineering Professional
email: imandic@devtonomy.net
description: "Personal portfolio"


# Team names, titles and social links
people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Ilija Mandic
  pic: 4
  position: Software Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

#- name: Ilija Mandic
#  pic: 4
#  position: Lead Developer
#  social:
     - title: twitter
       url: Dirkintruder
     - title: facebook
       url:  https://www.facebook.com/ilija.mandic.165
     - title: github
       url: https://github.com/imandicdev

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/Dirkintruder
  - title: facebook
    url: https://www.facebook.com/ilija.mandic.165
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/imandicdev

# Postal address (add as many lines as necessary)
address:
  - line: Kedrova 4
  - line: Belgrade, Serbia, 11000


# Build settings
markdown: kramdown
permalink: pretty
